# TODO add more examples
# - React
# - TypeScript
# - Stylesheets - Sass, Less, Stylus and Css, PostCSS
# - CoffeeScript
# - SWC
# - angular
# - coffee
# - elm
# - erb
# - react
# - stimulus
# - svelte
# - typescript
# - vue
example_type_data:
  -
    name: basic
    generator_options: ""
